### ISSUE TITLE
11. Som en bruger af systemet vil jeg gerne have feedback på om der sker fejl inde bag systemet, så jeg kan tjekke om mine data er gemt korrekt eller ej.

### ISSUE THREAD

**Issue by AeselCSS** [AeselCSS/miniCrud#11]

**Comment by AliHMohammad** [comment]
Jeg tror der menes ren console.logs ved good to go eller console.error ved fejl. De skal indsættes der, hvor vi laver fetch metoder under if(res.ok) statement

**Comment by AeselCSS** [comment]
Jeg læser det lidt anderledes.
En bruger vil jo aldrig skulle kigge i console, hvorfor jeg tænker at de ønsker en modal med "An error occurred, please fix something..."
En sådan fejlhåndtering skal være på create og update i hvert fald, spørgsmålet er, om det er meningsfuldt at have det på delete?
