### ISSUE TITLE
Bugs (kig desc)

### ISSUE THREAD

**Issue by AliHMohammad** [AeselCSS/miniCrud#24]

**Comment by AliHMohammad** [comment]
Bug nr.1: Youtube-video afspilles fortsat, efter modal lukkes.

**Comment by AliHMohammad** [comment]
Bug nr.2: Ved sletning af en af vores importeret film, gives error ved prepareData funktion ifm. id

Mulig årsag: Når vi importerer vores data i Firebase, bliver de nummeret 0, 1, 2.. i stedet for random strings

**Comment by AliHMohammad** [comment]
Bug nr 2: Vi har fundet en workaround. Se kommentar i prepareData func

**Comment by Forkeh** [comment]
Bug: Får fejl efter man har åbnet Add Movie modal og herefter prøver at åbne en ny modal

**Uncaught TypeError: can't access property "innerHTML", dialogContent is null**

**Comment by AeselCSS** [comment]
@Forkeh er det ikke bare fordi jeg ikke har fået ændret den dialog til det "nye" format, så funktionen showAddMovieModal() starter med at tømme hele dialog tagget ved document.querySelector("#dialog-modal").innerHTML = "";
og dermed kan hverken close button eller #dialog-content findes af de næste funktioner
